### ISSUE TITLE
抓取元件过程中, 会错误地选取目标点

### ISSUE THREAD

**Issue by Baileyus** [dukelec/cd_pnp#18]
现象如下:
1. 获取目标中(snap)
2. 找不到目标
3. 手动暂停(空格)
4. 手移动托盘, 使元件位于视野中
5. 手动继续(空格)
6. 直接跳过多次校准流程, 吸嘴马上朝着错误的坐标吸取

**Comment by dukelec** [comment]
Solved by commit: 1537da9
